#!/usr/bin/env python3
"""Encode unmodified Adwaita icons as Windows icon resources.

Requires Pillow and resvg-py. Icons from the current theme are rasterized
directly from the upstream SVG, and their 16-pixel frame is the upstream
16x16 PNG when one exists. Icons named with a "legacy:" prefix come from
adwaita-icon-theme-legacy, which ships PNGs only; their frames are those PNGs.
"""

import io
from pathlib import Path
import struct

from PIL import Image
import resvg_py


SIZES = (16, 20, 24, 32, 40, 48, 64, 96, 128, 256)
LEGACY_SIZES = (16, 24, 32, 48)
EMBLEM_SIZES = (16, 32, 48)
SHELL32 = "dll/win32/shell32/res/icons/"
SETUPAPI = "dll/win32/setupapi/res/"
INETCPL = "dll/cpl/inetcpl/resources/"
NETCFGX = "dll/win32/netcfgx/res/"
SYSDM = "dll/cpl/sysdm/resources/"
PIFMGR = "subsystems/mvdm/pifmgr/res_alt/"
TOOLBAR = "dll/win32/browseui/res/toolbar/"
CMICONTROL = "drivers/wdm/audio/drivers/CMIDriver/cmicontrol/"
TARGETS = (
    ("mimetypes/application-x-generic", SHELL32, (1,)),
    ("mimetypes/x-office-document", SHELL32, (2,)),
    ("mimetypes/application-x-executable", SHELL32, (3,)),
    ("places/folder", SHELL32, (4, 147)),
    ("status/folder-open", SHELL32, (5,)),
    ("legacy:legacy/media-floppy", SHELL32, (6, 7, 233, 305)),
    ("devices/drive-removable-media", SHELL32, (8, 312, 313)),
    ("devices/drive-harddisk", SHELL32, (9, 166)),
    ("places/folder-remote", SHELL32, (10, 172, 193, 258)),
    ("legacy:legacy/network-offline", SHELL32, (11, 49, 54)),
    ("devices/drive-optical", SHELL32, (12, 291)),
    ("mimetypes/application-x-firmware", SHELL32, (13,)),
    ("legacy:legacy/applications-internet", SHELL32, (14, 178, 244)),
    ("places/network-server", SHELL32, (15, 300, 301, 1003)),
    ("devices/computer", SHELL32, (16, 43, 282)),
    ("devices/printer", SHELL32, (17, 38, 138, 139, 168, 245, 1002)),
    ("places/network-workgroup", SHELL32, (18, 19, 259)),
    ("legacy:legacy/applications-other", SHELL32, (20, 37, 326)),
    ("legacy:legacy/document-open-recent", SHELL32, (21, 327)),
    ("legacy:legacy/preferences-system", SHELL32, (22, 36, 137, 321, 330)),
    ("legacy:legacy/system-search", SHELL32, (23, 281, 323)),
    ("legacy:legacy/help-browser", SHELL32, (24, 263, 324)),
    ("legacy:legacy/system-run", SHELL32, (25, 160, 328)),
    ("legacy:legacy/preferences-desktop-screensaver", SHELL32, (26,)),
    ("legacy:legacy/media-eject", SHELL32, (27, 331)),
    ("legacy:legacy/system-shutdown", SHELL32, (28, 221, 329, 8240)),
    ("places/user-trash", SHELL32, (32, 191)),
    ("status/user-trash-full", SHELL32, (33, 142, 143, 144, 192, 240)),
    ("legacy:legacy/modem", SHELL32, (34, 196, 197, 198, 199, 1011)),
    ("places/user-desktop", SHELL32, (35,)),
    ("legacy:legacy/preferences-desktop-font", SHELL32, (39,)),
    ("legacy:legacy/preferences-system-windows", SHELL32, (40, 177, 180, 184)),
    ("devices/media-optical", SHELL32, (41, 222, 228, 260, 261, 262, 266, 292, 293, 294,
                                        295, 296, 297, 298, 302, 304, 318, 320)),
    ("legacy:legacy/emblem-favorite", SHELL32, (44, 173, 322)),
    ("legacy:legacy/system-log-out", SHELL32, (45, 325)),
    ("legacy:legacy/system-file-manager", SHELL32, (46, 182, 183, 210)),
    ("legacy:legacy/system-software-update", SHELL32, (47,)),
    ("legacy:legacy/system-lock-screen", SHELL32, (48,)),
    ("legacy:legacy/edit-copy", SHELL32, (133, 223, 243)),
    ("legacy:legacy/document-open", SHELL32, (134,)),
    ("legacy:legacy/preferences-system-search", SHELL32, (135,)),
    ("devices/printer-network", SHELL32, (140, 169, 311, 1010)),
    ("legacy:legacy/document-print", SHELL32, (141, 170, 252, 1006)),
    ("legacy:legacy/view-refresh", SHELL32, (145,)),
    ("places/folder-drag-accept", SHELL32, (146, 256, 264)),
    ("legacy:legacy/preferences-other", SHELL32, (148,)),
    ("legacy:legacy/document-properties", SHELL32, (151, 174)),
    ("mimetypes/text-x-generic", SHELL32, (152,)),
    ("mimetypes/text-x-script", SHELL32, (153,)),
    ("mimetypes/application-x-sharedlib", SHELL32, (154,)),
    ("mimetypes/font-x-generic", SHELL32, (155, 156, 157)),
    ("legacy:legacy/edit-delete", SHELL32, (161, 338, 16710, 16715, 16717, 16718, 16721)),
    ("legacy:legacy/document-save", SHELL32, (165,)),
    ("devices/drive-multidisk", SHELL32, (167,)),
    ("mimetypes/x-office-presentation", SHELL32, (171, 249, 275)),
    ("legacy:legacy/preferences-system-network", SHELL32, (175, 257, 273)),
    ("legacy:legacy/network-idle", SHELL32, (176,)),
    ("legacy:legacy/network-transmit-receive", SHELL32, (179,)),
    ("legacy:legacy/preferences-desktop-wallpaper", SHELL32, (181,)),
    ("legacy:legacy/window-new", SHELL32, (185,)),
    ("devices/input-mouse", SHELL32, (186, 187, 229)),
    ("legacy:legacy/security-high", SHELL32, (194,)),
    ("legacy:legacy/process-stop", SHELL32, (200, 254)),
    ("legacy:legacy/system-users", SHELL32, (220, 269, 279)),
    ("mimetypes/video-x-generic", SHELL32, (224, 227)),
    ("mimetypes/audio-x-generic", SHELL32, (225, 247)),
    ("mimetypes/image-x-generic", SHELL32, (226, 251)),
    ("legacy:legacy/dialog-error", SHELL32, (234,)),
    ("places/folder-documents", SHELL32, (235,)),
    ("places/folder-pictures", SHELL32, (236,)),
    ("places/folder-music", SHELL32, (237,)),
    ("places/folder-videos", SHELL32, (238,)),
    ("places/folder-download", SHELL32, ("downloads",)),
    ("legacy:legacy/document-send", SHELL32, (241, 1005)),
    ("legacy:legacy/media-playback-start", SHELL32, (246,)),
    ("legacy:legacy/camera-photo", SHELL32, (248, 309, 316)),
    ("devices/video-display", SHELL32, (250,)),
    ("legacy:legacy/emblem-default", SHELL32, (253, 1007)),
    ("legacy:legacy/edit-undo", SHELL32, (255,)),
    ("legacy:legacy/mail-send", SHELL32, (265,)),
    ("places/folder-publicshare", SHELL32, (267,)),
    ("legacy:legacy/preferences-desktop-accessibility", SHELL32, (268,)),
    ("legacy:legacy/preferences-desktop-theme", SHELL32, (270,)),
    ("legacy:legacy/system-software-install", SHELL32, (271,)),
    ("legacy:legacy/preferences-desktop-peripherals", SHELL32, (272,)),
    ("legacy:legacy/applications-system", SHELL32, (274,)),
    ("legacy:legacy/preferences-desktop-locale", SHELL32, (276,)),
    ("legacy:legacy/audio-speakers", SHELL32, (277,)),
    ("legacy:legacy/utilities-terminal", SHELL32, (278,)),
    ("devices/input-keyboard", SHELL32, (283,)),
    ("legacy:legacy/help-contents", SHELL32, (289, 1004)),
    ("legacy:legacy/go-next", SHELL32, (290,)),
    ("legacy:legacy/multimedia-player", SHELL32, (299,)),
    ("devices/media-flash", SHELL32, (303, 307, 308)),
    ("devices/phone", SHELL32, (310,)),
    ("legacy:legacy/pda", SHELL32, (314,)),
    ("devices/scanner", SHELL32, (315,)),
    ("legacy:legacy/camera-video", SHELL32, (317,)),
    ("legacy:legacy/folder-new", SHELL32, (319,)),
    ("legacy:legacy/edit-find", SHELL32, (337,)),
    ("legacy:legacy/web-browser", SHELL32, (512,)),
    ("legacy:legacy/dialog-information", SHELL32, (1001,)),
    ("legacy:legacy/printer-printing", SHELL32, (1008, 1009)),
    ("devices/video-display", SETUPAPI, (1,)),
    ("devices/input-mouse", SETUPAPI, (2,)),
    ("devices/input-keyboard", SETUPAPI, (3,)),
    ("devices/printer", SETUPAPI, (4,)),
    ("legacy:legacy/network-wired", SETUPAPI, (5,)),
    ("devices/computer", SETUPAPI, (7, 27)),
    ("mimetypes/application-x-firmware", SETUPAPI, (9, 10, 28, 159)),
    ("devices/media-flash", SETUPAPI, (11,)),
    ("legacy:legacy/dialog-question", SETUPAPI, (18,)),
    ("mimetypes/application-x-executable", SETUPAPI, (19,)),
    ("devices/media-removable", SETUPAPI, (20,)),
    ("devices/input-tablet", SETUPAPI, (24,)),
    ("mimetypes/application-certificate", SETUPAPI, (40,)),
    ("legacy:legacy/dialog-warning", SETUPAPI, (42,)),
    ("legacy:legacy/media-floppy", SETUPAPI, (50, 105)),
    ("devices/drive-optical", SETUPAPI, (51,)),
    ("places/network-server", SETUPAPI, (52,)),
    ("devices/drive-harddisk", SETUPAPI, (53,)),
    ("legacy:legacy/system-software-install", SETUPAPI, (54,)),
    ("legacy:legacy/process-stop", SETUPAPI, (161,)),
    ("mimetypes/application-certificate", INETCPL, ("certificates",)),
    ("legacy:legacy/document-open-recent", INETCPL, ("history",)),
    ("legacy:legacy/go-home", INETCPL, ("home",)),
    ("legacy:legacy/dialog-error", INETCPL, ("restricted",)),
    ("legacy:legacy/emblem-default", INETCPL, ("trusted",)),
    ("places/network-workgroup", NETCFGX, ("network",)),
    ("legacy:legacy/preferences-system-network", NETCFGX, ("internet",)),
    ("devices/computer", SYSDM, ("applet",)),
    ("mimetypes/application-x-firmware", SYSDM, ("addhw", "dev", "hwprofile")),
    ("legacy:legacy/preferences-system", SYSDM, ("devmgr",)),
    ("mimetypes/application-certificate", SYSDM, ("license",)),
    ("legacy:legacy/dialog-information", PIFMGR, ("09",)),
    ("devices/computer", PIFMGR, ("13",)),
    ("devices/input-keyboard", PIFMGR, ("14",)),
    ("mimetypes/application-x-firmware", PIFMGR, ("15",)),
    ("legacy:mimetypes/x-office-calendar", PIFMGR, ("16",)),
    ("legacy:legacy/help-browser", PIFMGR, ("32",)),
    ("legacy:legacy/audio-speakers", CMICONTROL, ("window",)),
    ("mimetypes/application-x-firmware", "dll/cpl/hdwwiz/resources/", ("applet",)),
    ("legacy:legacy/applications-system", "dll/cpl/main/resources/", ("admintools_folder",)),
    ("devices/input-keyboard", "dll/cpl/main/resources/", ("keyboard",)),
    ("devices/input-mouse", "dll/cpl/main/resources/", ("mouse",)),
    ("legacy:legacy/utilities-terminal", "dll/cpl/console/res/", ("terminal",)),
    ("legacy:legacy/appointment-soon", "dll/cpl/timedate/resources/", ("applet",)),
    ("legacy:legacy/preferences-desktop-display", "dll/cpl/desk/resources/", ("applet",)),
    ("legacy:legacy/preferences-desktop-theme", "dll/cpl/desk/resources/", ("personalization",)),
    ("legacy:legacy/preferences-desktop-accessibility", "dll/cpl/access/resources/", ("applet",)),
    ("devices/input-gaming", "dll/cpl/joy/", ("joy",)),
    ("legacy:legacy/applications-internet", "dll/cpl/inetcpl/", ("inetcpl",)),
    ("legacy:legacy/preferences-system-network", "dll/shellext/netshell/res/", ("netshell",)),
    ("legacy:legacy/applications-graphics", "dll/cpl/openglcfg/resources/", ("openglcfg",)),
    ("legacy:legacy/applications-graphics", "dll/cpl/wined3dcfg/resources/", ("wined3dcfg",)),
    ("legacy:legacy/modem", "dll/cpl/telephon/resources/", ("applet",)),
    ("legacy:legacy/ac-adapter", "dll/cpl/powercfg/resources/", ("ac",)),
    ("legacy:legacy/system-software-install", "dll/cpl/appwiz/resources/", ("applet",)),
    ("legacy:legacy/preferences-desktop-locale", "dll/cpl/intl/resources/", ("applet",)),
    ("legacy:legacy/media-eject", "dll/cpl/hotplug/resources/", (1,)),
    ("legacy:legacy/audio-speakers", "dll/cpl/mmsys/resources/", (3004,)),
    ("legacy:legacy/preferences-desktop-keyboard-shortcuts", "dll/cpl/input/resources/",
     ("keyboard-shortcuts",)),
    ("legacy:legacy/system-users", "dll/cpl/usrmgr/resources/", ("applet",)),
    ("legacy:legacy/system-file-manager", "dll/shellext/ntobjshex/resources/", (1,)),
    ("legacy:legacy/preferences-system", "dll/shellext/ntobjshex/resources/", (7,)),
    ("legacy:legacy/go-previous", TOOLBAR, ("01-back",)),
    ("legacy:legacy/go-next", TOOLBAR, ("02-forward",)),
    ("legacy:legacy/go-up", TOOLBAR, ("03-up",)),
    ("legacy:legacy/system-search", TOOLBAR, ("04-search",)),
    ("places/folder", TOOLBAR, ("05-folders",)),
    ("places/folder-drag-accept", TOOLBAR, ("06-move",)),
    ("legacy:legacy/edit-copy", TOOLBAR, ("07-copy",)),
    ("legacy:legacy/edit-delete", TOOLBAR, ("08-delete",)),
    ("legacy:legacy/edit-undo", TOOLBAR, ("09-undo",)),
    ("legacy:legacy/preferences-system-windows", TOOLBAR, ("10-views",)),
    ("legacy:legacy/go-down", TOOLBAR, ("11-dropdown",)),
    ("legacy:legacy/accessories-calculator", "base/applications/calc/res/",
     ("calc",)),
    ("legacy:legacy/accessories-character-map", "base/applications/charmap/res/",
     ("charmap",)),
    ("legacy:legacy/accessories-character-map", "base/applications/charmap_new/res/",
     ("charmap",)),
    ("legacy:legacy/edit-clear-all", "base/applications/cleanmgr/cleanmgr/resources/",
     ("cleanmgr",)),
    ("legacy:legacy/edit-paste", "base/applications/clipbrd/res/",
     ("clipbrd", "clpfile",)),
    ("legacy:legacy/system-software-install", "base/applications/cmdutils/rosget/res/",
     ("rosget",)),
    ("legacy:legacy/preferences-system", "base/applications/control/resources/",
     ("config",)),
    ("legacy:legacy/preferences-desktop-display", "base/applications/dxdiag/res/",
     ("dxdiag",)),
    ("mimetypes/font-x-generic", "base/applications/fontview/",
     ("ttf",)),
    ("legacy:legacy/applications-games", "base/applications/games/solitaire/",
     ("solitaire",)),
    ("legacy:legacy/applications-games", "base/applications/games/spider/",
     ("spider",)),
    ("legacy:legacy/applications-games", "base/applications/games/winmine/rc/",
     ("winemine",)),
    ("legacy:legacy/help-browser", "base/applications/hh/",
     ("hh",)),
    ("legacy:legacy/web-browser", "base/applications/iexplore/",
     ("iexplore",)),
    ("legacy:legacy/preferences-desktop-keyboard-shortcuts", "base/applications/kbswitch/res/",
     ("kbswitch",)),
    ("legacy:legacy/edit-find", "base/applications/magnify/res/",
     ("magnify",)),
    ("legacy:legacy/applications-utilities", "base/applications/mmc/resources/",
     ("mmc",)),
    ("legacy:legacy/multimedia-player", "base/applications/mplay32/resources/",
     ("mplay32",)),
    ("legacy:legacy/preferences-system", "base/applications/msconfig/res/",
     ("msconfig",)),
    ("legacy:legacy/preferences-system", "base/applications/msconfig_new/res/",
     ("msconfig",)),
    ("mimetypes/application-certificate", "base/applications/mscutils/certmgr/resources/",
     ("certmgr",)),
    ("legacy:legacy/preferences-desktop-peripherals", "base/applications/mscutils/devmgmt/",
     ("devmgmt",)),
    ("devices/drive-harddisk", "base/applications/mscutils/diskmgmt/res/",
     ("hdisk",)),
    ("legacy:legacy/edit-copy", "base/applications/mscutils/eventvwr/res/",
     ("copy",)),
    ("legacy:legacy/dialog-error", "base/applications/mscutils/eventvwr/res/",
     ("error",)),
    ("mimetypes/text-x-generic", "base/applications/mscutils/eventvwr/res/",
     ("eventlog",)),
    ("legacy:legacy/document-properties", "base/applications/mscutils/eventvwr/res/",
     ("eventvwr",)),
    ("places/folder", "base/applications/mscutils/eventvwr/res/",
     ("folder",)),
    ("status/folder-open", "base/applications/mscutils/eventvwr/res/",
     ("folderopen",)),
    ("legacy:legacy/dialog-information", "base/applications/mscutils/eventvwr/res/",
     ("info",)),
    ("legacy:legacy/dialog-password", "base/applications/mscutils/eventvwr/res/",
     ("key",)),
    ("legacy:legacy/changes-prevent", "base/applications/mscutils/eventvwr/res/",
     ("lock",)),
    ("legacy:legacy/go-down", "base/applications/mscutils/eventvwr/res/",
     ("next_event",)),
    ("legacy:legacy/go-up", "base/applications/mscutils/eventvwr/res/",
     ("prev_event",)),
    ("legacy:legacy/dialog-warning", "base/applications/mscutils/eventvwr/res/",
     ("warning",)),
    ("mimetypes/application-x-executable", "base/applications/mscutils/servman/res/",
     ("driver",)),
    ("legacy:legacy/dialog-question", "base/applications/mscutils/servman/res/",
     ("nodepends",)),
    ("legacy:legacy/applications-system", "base/applications/mscutils/servman/res/",
     ("system",)),
    ("mimetypes/text-html", "base/applications/mshta/",
     ("mshta",)),
    ("legacy:legacy/applications-graphics", "base/applications/mspaint/img/",
     ("paint",)),
    ("legacy:legacy/preferences-desktop-theme", "base/applications/mstsc/res/",
     ("colors",)),
    ("legacy:legacy/preferences-system-network", "base/applications/mstsc/res/",
     ("connection",)),
    ("devices/computer", "base/applications/mstsc/res/",
     ("logon",)),
    ("legacy:legacy/preferences-desktop-remote-desktop", "base/applications/mstsc/res/",
     ("mstsc",)),
    ("devices/video-display", "base/applications/mstsc/res/",
     ("remote",)),
    ("legacy:legacy/utilities-terminal", "base/applications/network/telnet/",
     ("telnet",)),
    ("legacy:legacy/accessories-text-editor", "base/applications/notepad/res/",
     ("notepad",)),
    ("devices/input-keyboard", "base/applications/osk/res/",
     ("osk",)),
    ("legacy:legacy/applications-other", "base/applications/rapps/res/",
     ("apps",)),
    ("legacy:legacy/system-software-update", "base/applications/rapps/res/",
     ("appupd", "updatedb",)),
    ("status/image-missing", "base/applications/rapps/res/",
     ("brokenimg",)),
    ("places/folder", "base/applications/rapps/res/",
     ("cat",)),
    ("mimetypes/audio-x-generic", "base/applications/rapps/res/cats/",
     ("audio",)),
    ("legacy:legacy/applications-development", "base/applications/rapps/res/cats/",
     ("devel",)),
    ("mimetypes/application-x-firmware", "base/applications/rapps/res/cats/",
     ("drivers",)),
    ("legacy:legacy/accessories-dictionary", "base/applications/rapps/res/cats/",
     ("edu",)),
    ("legacy:legacy/applications-engineering", "base/applications/rapps/res/cats/",
     ("engineer",)),
    ("mimetypes/x-office-spreadsheet", "base/applications/rapps/res/cats/",
     ("finance",)),
    ("legacy:legacy/applications-games", "base/applications/rapps/res/cats/",
     ("games",)),
    ("legacy:legacy/applications-graphics", "base/applications/rapps/res/cats/",
     ("graphics",)),
    ("legacy:legacy/applications-internet", "base/applications/rapps/res/cats/",
     ("internet",)),
    ("mimetypes/application-x-sharedlib", "base/applications/rapps/res/cats/",
     ("libs",)),
    ("legacy:legacy/applications-office", "base/applications/rapps/res/cats/",
     ("office",)),
    ("legacy:legacy/applications-other", "base/applications/rapps/res/cats/",
     ("other",)),
    ("legacy:legacy/applications-science", "base/applications/rapps/res/cats/",
     ("science",)),
    ("legacy:legacy/preferences-desktop-theme", "base/applications/rapps/res/cats/",
     ("themes",)),
    ("legacy:legacy/applications-utilities", "base/applications/rapps/res/cats/",
     ("tools",)),
    ("mimetypes/video-x-generic", "base/applications/rapps/res/cats/",
     ("video",)),
    ("legacy:legacy/application-exit", "base/applications/rapps/res/",
     ("exit",)),
    ("legacy:legacy/system-software-install", "base/applications/rapps/res/",
     ("install", "main",)),
    ("legacy:legacy/document-properties", "base/applications/rapps/res/",
     ("modify",)),
    ("legacy:legacy/view-refresh", "base/applications/rapps/res/",
     ("refresh",)),
    ("legacy:legacy/edit-select-all", "base/applications/rapps/res/",
     ("select",)),
    ("legacy:legacy/preferences-system", "base/applications/rapps/res/",
     ("settings",)),
    ("legacy:legacy/edit-delete", "base/applications/rapps/res/",
     ("uninstall",)),
    ("legacy:legacy/system-software-install", "base/applications/rapps_com/",
     ("main",)),
    ("legacy:legacy/applications-system", "base/applications/regedit/res/",
     ("regedit",)),
    ("mimetypes/text-x-script", "base/applications/regedit/res/",
     ("regfile",)),
    ("legacy:legacy/applications-system", "base/applications/regedt32/res/",
     ("regedt32",)),
    ("legacy:legacy/preferences-desktop-screensaver", "base/applications/screensavers/3dtext/res/",
     ("icon_3dtext",)),
    ("legacy:legacy/preferences-desktop-screensaver", "base/applications/screensavers/logon/res/",
     ("icon_logon",)),
    ("devices/microphone", "base/applications/sndrec32/resources/",
     ("record-app",)),
    ("legacy:legacy/multimedia-volume-control", "base/applications/sndvol32/resources/",
     ("sndvol32",)),
    ("legacy:legacy/applications-system", "base/applications/taskmgr/res/",
     ("taskmgr",)),
    ("mimetypes/application-x-executable", "base/applications/taskmgr/res/",
     ("window", "windowsm",)),
    ("legacy:legacy/applications-system", "base/applications/taskmgr11/res/",
     ("taskmgr11",)),
    ("legacy:legacy/preferences-desktop-accessibility", "base/applications/utilman/res/",
     ("utilman",)),
    ("legacy:legacy/help-contents", "base/applications/winhlp32/",
     ("winhelp",)),
    ("mimetypes/x-office-document", "base/applications/wordpad/res/",
     ("document",)),
    ("legacy:legacy/applications-office", "base/applications/wordpad/",
     ("wordpad",)),
    ("legacy:legacy/applications-office", "base/applications/write/",
     ("write",)),
    ("legacy:legacy/system-software-update", "base/applications/wusa/res/",
     ("setup",)),
    ("legacy:legacy/preferences-desktop-locale", "base/ctf/ctfmon/res/",
     ("ctfmon",)),
    ("legacy:legacy/preferences-desktop-locale", "base/ctf/msutb/res/",
     ("earth",)),
    ("devices/drive-harddisk", "base/setup/reactos/res/",
     ("drive_disk", "partition",)),
    ("legacy:legacy/system-software-install", "base/setup/reactos/res/",
     ("setup",)),
    ("legacy:legacy/utilities-terminal", "base/shell/cmd/res/",
     ("terminal",)),
    ("legacy:legacy/system-file-manager", "base/shell/explorer/res/ico/",
     (101,)),
    ("devices/printer", "base/shell/explorer/res/ico/",
     (102,)),
    ("places/user-desktop", "base/shell/explorer/res/ico/",
     (103,)),
    ("legacy:legacy/printer-error", "base/shell/explorer/res/ico/",
     (104,)),
    ("places/user-trash", "base/shell/explorer/res/ico/",
     (108,)),
    ("legacy:legacy/dialog-information", "base/shell/explorer/res/ico/",
     (109,)),
    ("legacy:legacy/dialog-warning", "base/shell/explorer/res/ico/",
     (110,)),
    ("legacy:legacy/dialog-error", "base/shell/explorer/res/ico/",
     (111,)),
    ("devices/computer", "base/shell/explorer/res/ico/",
     (205,)),
    ("places/folder", "base/shell/explorer/res/ico/",
     (252,)),
    ("legacy:legacy/web-browser", "base/shell/explorer/res/ico/",
     (253,)),
    ("legacy:legacy/mail-unread", "base/shell/explorer/res/ico/",
     (254, 256,)),
    ("places/folder", "base/shell/progman/res/",
     ("group", "group_common", "group_personal",)),
    ("legacy:legacy/utilities-terminal", "base/shell/progman/res/",
     ("terminal",)),
    ("legacy:legacy/system-software-install", "base/system/msiexec/",
     ("msiexec",)),
    ("mimetypes/application-x-executable", "base/system/rundll32/res/",
     ("main",)),
    ("mimetypes/application-x-executable", "base/system/runonce/res/",
     ("icon",)),
    ("legacy:legacy/dialog-password", "base/system/winlogon/res/",
     ("winlogon",)),
    ("legacy:legacy/utilities-terminal", "boot/freeldr/fdebug/",
     ("fdebug",)),
    ("mimetypes/application-x-executable", "dll/cpl/appwiz/resources/",
     (1501,)),
    ("legacy:legacy/system-software-install", "dll/cpl/appwiz/resources/",
     (1502,)),
    ("places/user-trash", "dll/cpl/appwiz/resources/",
     (1503,)),
    ("places/folder-download", "dll/cpl/appwiz/resources/",
     (1504,)),
    ("legacy:legacy/applications-internet", "dll/cpl/appwiz/resources/",
     (1505,)),
    ("legacy:legacy/system-search", "dll/cpl/hdwwiz/resources/",
     ("search",)),
    ("legacy:legacy/dialog-warning", "dll/cpl/hdwwiz/resources/",
     ("warning",)),
    ("legacy:legacy/applications-internet", "dll/cpl/inetcpl/resources/",
     ("inetcpl",)),
    ("devices/input-keyboard", "dll/cpl/input/resources/",
     ("keyboard",)),
    ("mimetypes/application-certificate", "dll/cpl/liccpa/resources/",
     ("cpl_icon1",)),
    ("places/folder", "dll/cpl/main/resources/",
     ("folder_closed",)),
    ("status/folder-open", "dll/cpl/main/resources/",
     ("folder_open",)),
    ("legacy:legacy/changes-prevent", "dll/cpl/main/resources/",
     ("lock_key",)),
    ("devices/input-mouse", "dll/cpl/main/resources/",
     ("mouse_button", "mouse_hide", "mouse_left", "mouse_pointer", "mouse_right", "mouse_speed", "mouse_trails", "mouse_wheel",)),
    ("devices/input-keyboard", "dll/cpl/main/resources/",
     ("repeat_delay", "repeat_rate",)),
    ("mimetypes/audio-x-generic", "dll/cpl/mmsys/resources/",
     (4353,)),
    ("legacy:legacy/audio-speakers", "dll/cpl/mmsys/resources/",
     (4354, 4363, 4367, 4368, 4379, "speaker",)),
    ("devices/input-gaming", "dll/cpl/mmsys/resources/",
     (4361,)),
    ("legacy:legacy/camera-video", "dll/cpl/mmsys/resources/",
     (4364,)),
    ("places/folder-music", "dll/cpl/mmsys/resources/",
     (4366,)),
    ("devices/microphone", "dll/cpl/mmsys/resources/",
     (4369, 4378, 4380,)),
    ("legacy:legacy/audio-volume-muted", "dll/cpl/mmsys/resources/",
     (4390, 4393,)),
    ("legacy:legacy/system-shutdown", "dll/cpl/mmsys/resources/",
     (4394,)),
    ("legacy:legacy/media-playback-start", "dll/cpl/mmsys/resources/",
     ("play",)),
    ("legacy:legacy/media-playback-stop", "dll/cpl/mmsys/resources/",
     ("stop",)),
    ("legacy:legacy/battery-full-charging", "dll/cpl/powercfg/resources/",
     ("acdc", "batterycharginghigh",)),
    ("legacy:legacy/battery-good-charging", "dll/cpl/powercfg/resources/",
     ("batterycharging", "batterycharginghalf",)),
    ("legacy:legacy/battery-caution-charging", "dll/cpl/powercfg/resources/",
     ("batterychargingcritical",)),
    ("legacy:legacy/battery-low-charging", "dll/cpl/powercfg/resources/",
     ("batterycharginglow",)),
    ("legacy:legacy/battery-caution", "dll/cpl/powercfg/resources/",
     ("batterycritical",)),
    ("legacy:legacy/battery-full", "dll/cpl/powercfg/resources/",
     ("batteryfull", "batteryhigh",)),
    ("legacy:legacy/battery-good", "dll/cpl/powercfg/resources/",
     ("batteryhalf",)),
    ("legacy:legacy/battery-low", "dll/cpl/powercfg/resources/",
     ("batterylow",)),
    ("legacy:legacy/battery-missing", "dll/cpl/powercfg/resources/",
     ("batteryunknown", "nobattery",)),
    ("legacy:legacy/battery", "dll/cpl/powercfg/resources/",
     ("dc",)),
    ("legacy:legacy/preferences-desktop-screensaver", "dll/cpl/powercfg/resources/",
     ("hibernate",)),
    ("devices/video-display", "dll/cpl/powercfg/resources/",
     ("screen",)),
    ("legacy:legacy/system-users", "dll/cpl/usrmgr/resources/",
     ("group",)),
    ("legacy:legacy/changes-prevent", "dll/cpl/usrmgr/resources/",
     ("locked",)),
    ("status/avatar-default", "dll/cpl/usrmgr/resources/",
     ("user",)),
    ("mimetypes/package-x-generic", "dll/shellext/cabview/res/",
     ("folder",)),
    ("mimetypes/application-certificate", "dll/shellext/cryptext/res/",
     ("cerfile",)),
    ("mimetypes/application-x-firmware", "dll/shellext/deskadp/resources/",
     ("adapter",)),
    ("devices/video-display", "dll/shellext/deskmon/resources/",
     ("monitor",)),
    ("places/network-workgroup", "dll/shellext/netplwiz/res/",
     (4400,)),
    ("legacy:legacy/network-error", "dll/shellext/netshell/res/",
     ("neterror",)),
    ("legacy:legacy/network-idle", "dll/shellext/netshell/res/",
     ("netidle",)),
    ("legacy:legacy/network-offline", "dll/shellext/netshell/res/",
     ("netoff",)),
    ("legacy:legacy/network-receive", "dll/shellext/netshell/res/",
     ("netrec",)),
    ("legacy:legacy/preferences-system-network", "dll/shellext/netshell/res/",
     ("netsetup",)),
    ("legacy:legacy/network-transmit", "dll/shellext/netshell/res/",
     ("nettrans",)),
    ("legacy:legacy/network-transmit-receive", "dll/shellext/netshell/res/",
     ("nettrrec",)),
    ("places/folder", "dll/shellext/ntobjshex/resources/",
     (2,)),
    ("status/folder-open", "dll/shellext/ntobjshex/resources/",
     (3,)),
    ("mimetypes/application-x-generic", "dll/shellext/ntobjshex/resources/",
     (4,)),
    ("legacy:legacy/applications-system", "dll/shellext/ntobjshex/resources/",
     (5,)),
    ("legacy:legacy/network-wired", "dll/shellext/ntobjshex/resources/",
     (6,)),
    ("mimetypes/text-x-generic", "dll/shellext/ntobjshex/resources/",
     (8,)),
    ("places/folder", "dll/shellext/shellbtrfs/",
     ("subvol",)),
    ("legacy:legacy/ac-adapter", "dll/shellext/stobject/resources/",
     (1,)),
    ("devices/drive-removable-media", "dll/shellext/stobject/resources/",
     (2,)),
    ("legacy:legacy/audio-volume-high", "dll/shellext/stobject/resources/",
     (3,)),
    ("legacy:legacy/audio-volume-muted", "dll/shellext/stobject/resources/",
     (4,)),
    ("legacy:legacy/battery-caution", "dll/shellext/stobject/resources/battery/",
     ("0",)),
    ("legacy:legacy/battery-low", "dll/shellext/stobject/resources/battery/",
     (1, 2,)),
    ("legacy:legacy/battery-good", "dll/shellext/stobject/resources/battery/",
     (3,)),
    ("legacy:legacy/battery-full", "dll/shellext/stobject/resources/battery/",
     (4, 5,)),
    ("legacy:legacy/ac-adapter", "dll/shellext/stobject/resources/battery/",
     ("ac",)),
    ("legacy:legacy/battery-caution-charging", "dll/shellext/stobject/resources/battery/",
     ("charging0",)),
    ("legacy:legacy/battery-low-charging", "dll/shellext/stobject/resources/battery/",
     ("charging1",)),
    ("legacy:legacy/battery-good-charging", "dll/shellext/stobject/resources/battery/",
     ("charging2", "charging3",)),
    ("legacy:legacy/battery-full-charging", "dll/shellext/stobject/resources/battery/",
     ("charging4",)),
    ("legacy:legacy/battery-missing", "dll/shellext/stobject/resources/battery/",
     ("error",)),
    ("devices/drive-removable-media", "dll/shellext/stobject/resources/hotplug/",
     ("0", 1,)),
    ("mimetypes/package-x-generic", "dll/shellext/zipfldr/res/",
     ("zipfldr",)),
    ("legacy:legacy/battery", "dll/win32/batt/resources/",
     ("battery",)),
    ("legacy:legacy/network-wireless", "dll/win32/bthci/resources/",
     ("bluetooth",)),
    ("legacy:legacy/dialog-error", "dll/win32/comctl32/",
     ("idi_tt_error_md", "idi_tt_error_sm",)),
    ("legacy:legacy/dialog-information", "dll/win32/comctl32/",
     ("idi_tt_info_md", "idi_tt_info_sm",)),
    ("legacy:legacy/dialog-warning", "dll/win32/comctl32/",
     ("idi_tt_warn_md", "idi_tt_warn_sm",)),
    ("devices/drive-optical", "dll/win32/comdlg32/res/icons/",
     ("cdrom",)),
    ("legacy:legacy/media-floppy", "dll/win32/comdlg32/res/icons/",
     ("floppy",)),
    ("places/folder", "dll/win32/comdlg32/res/icons/",
     ("folder",)),
    ("status/folder-open", "dll/win32/comdlg32/res/icons/",
     ("folder2",)),
    ("devices/drive-harddisk", "dll/win32/comdlg32/res/icons/",
     ("hdisk",)),
    ("places/folder-remote", "dll/win32/comdlg32/res/icons/",
     ("network",)),
    ("devices/computer", "dll/win32/devmgr/resources/",
     ("computer",)),
    ("legacy:legacy/help-browser", "dll/win32/hhctrl.ocx/res/",
     ("hh",)),
    ("mimetypes/text-html", "dll/win32/ieframe/resources/",
     ("pages",)),
    ("legacy:legacy/system-software-install", "dll/win32/iernonce/res/",
     ("setup",)),
    ("legacy:legacy/modem", "dll/win32/modemui/res/",
     (5100, 700, 701, 702, 703,)),
    ("devices/input-keyboard", "dll/win32/msgina/resources/",
     (109,)),
    ("mimetypes/application-x-firmware", "dll/win32/msgina/resources/",
     (110,)),
    ("legacy:legacy/system-lock-screen", "dll/win32/msgina/resources/",
     (115,)),
    ("legacy:legacy/computer-fail", "dll/win32/msgina/resources/",
     (13,)),
    ("legacy:legacy/system-log-out", "dll/win32/msgina/resources/",
     (21, "ico_logoff",)),
    ("legacy:legacy/system-shutdown", "dll/win32/msgina/resources/",
     (22, "shutdown",)),
    ("mimetypes/text-html", "dll/win32/msxml3/res/",
     (128,)),
    ("mimetypes/text-x-script", "dll/win32/msxml3/res/",
     (129,)),
    ("places/network-workgroup", "dll/win32/netid/res/",
     (101,)),
    ("legacy:legacy/dialog-warning", "dll/win32/netid/res/",
     (102,)),
    ("legacy:legacy/modem", "dll/win32/rasdlg/res/icons/",
     (15102, 52, 55,)),
    ("mimetypes/application-x-firmware", "dll/win32/rasdlg/res/icons/",
     (53,)),
    ("legacy:legacy/network-wired", "dll/win32/rasdlg/res/icons/",
     (54, 58,)),
    ("devices/computer", "dll/win32/rasdlg/res/icons/",
     (56, 57,)),
    ("legacy:legacy/preferences-system-network", "dll/win32/rasdlg/res/icons/",
     (562,)),
    ("legacy:legacy/network-idle", "dll/win32/rasdlg/res/icons/",
     (563,)),
    ("devices/video-display", "dll/win32/rasdlg/res/icons/",
     (59,)),
    ("legacy:legacy/network-wired", "dll/win32/setupapi/res/",
     (23, 26, 6,)),
    ("legacy:legacy/network-error", "dll/win32/setupapi/res/",
     (43,)),
    ("devices/video-display", "dll/win32/setupapi/res/",
     (8,)),
    ("places/folder", "dll/win32/shell32/res/icons/",
     (1700,)),
    ("emblem:emblems/emblem-shared", "dll/win32/shell32/res/icons/",
     (29,)),
    ("emblem:emblems/emblem-symbolic-link", "dll/win32/shell32/res/icons/",
     (30,)),
    ("mimetypes/image-x-generic", "dll/win32/shimgvw/res/",
     ("bmp", "main", "png",)),
    ("legacy:legacy/go-home", "dll/win32/syssetup/resources/",
     (1,)),
    ("legacy:legacy/contact-new", "dll/win32/syssetup/resources/",
     (2,)),
    ("legacy:mimetypes/x-office-calendar", "dll/win32/syssetup/resources/",
     (3,)),
    ("legacy:legacy/preferences-desktop-locale", "dll/win32/syssetup/resources/",
     (4,)),
    ("legacy:legacy/system-users", "dll/win32/syssetup/resources/",
     (5,)),
    ("legacy:legacy/modem", "dll/win32/tapiui/res/",
     (201, 202,)),
    ("legacy:legacy/contact-new", "dll/win32/tapiui/res/",
     (203,)),
    ("legacy:legacy/dialog-password", "dll/win32/tapiui/res/",
     (504,)),
    ("legacy:legacy/preferences-desktop-theme", "dll/win32/themeui/",
     ("themeui",)),
    ("mimetypes/text-html", "dll/win32/url/res/",
     (102,)),
    ("legacy:legacy/system-users", "dll/win32/userenv/res/",
     ("userenv",)),
    ("legacy:legacy/applications-system", "modules/rosapps/applications/devutils/gdihv/",
     ("system",)),
    ("mimetypes/font-x-generic", "modules/rosapps/applications/devutils/vgafontedit/res/",
     ("doc",)),
    ("legacy:legacy/preferences-desktop-font", "modules/rosapps/applications/devutils/vgafontedit/res/",
     ("main",)),
    ("devices/drive-harddisk", "modules/rosapps/applications/fraginator/",
     ("icon1",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/blankscr/res/",
     ("icon_blankscr",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/butterflies/res/",
     ("icon_butterflies",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/circles/res/",
     ("icon_circles",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/cylfrac/res/",
     ("icon_cylfrac",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/matrix/",
     ("icon1",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/mazescr/res/",
     ("icon_mazescr",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/ssstars/res/",
     ("icon_stars",)),
    ("legacy:legacy/preferences-desktop-screensaver", "modules/rosapps/applications/screensavers/starfield/res/",
     ("icon_starfield",)),
    ("legacy:legacy/preferences-desktop-font", "modules/rosapps/applications/sysutils/fontsub/",
     ("fontsub",)),
    ("legacy:legacy/applets-screenshooter", "modules/rosapps/applications/sysutils/screenshot/",
     ("snap",)),
    ("legacy:legacy/preferences-system", "modules/rosapps/lib/vfdlib/res/",
     ("config",)),
    ("legacy:legacy/media-floppy", "modules/rosapps/lib/vfdlib/res/",
     ("image", "vfd",)),
    ("mimetypes/application-x-executable", "modules/rosapps/templates/mdi/res/",
     ("mdi", "small",)),
    ("legacy:legacy/accessories-text-editor", "modules/rosapps/templates/old_wordpad/res/",
     ("wordpad",)),
    ("devices/computer", "subsystems/mvdm/ntvdm/res/",
     ("ntvdm_pc_at_3d", "ntvdm_pc_at_brown", "ntvdm_pc_at_flat", "ntvdm_pc_at_grey", "ntvdm_pc_xt_3d", "ntvdm_pc_xt_brown", "ntvdm_pc_xt_flat", "ntvdm_pc_xt_grey", "pc_at", "pc_xt",)),
    ("legacy:legacy/utilities-terminal", "subsystems/mvdm/ntvdm/res/",
     ("vdm_dos",)),
    ("legacy:legacy/utilities-terminal", "subsystems/mvdm/pifmgr/res/",
     ("01vdm",)),
    ("legacy:legacy/dialog-warning", "win32ss/user/user32/resources/",
     ("oic_bang",)),
    ("legacy:legacy/dialog-error", "win32ss/user/user32/resources/",
     ("oic_hand",)),
    ("legacy:legacy/dialog-information", "win32ss/user/user32/resources/",
     ("oic_note",)),
    ("legacy:legacy/dialog-question", "win32ss/user/user32/resources/",
     ("oic_ques",)),
    ("mimetypes/application-x-executable", "win32ss/user/user32/resources/",
     ("oic_sample",)),
    ("legacy:legacy/utilities-terminal", "win32ss/user/winsrv/consrv/frontends/gui/res/",
     ("terminal",)),
)


def frames_for(assets, name):
    if name.startswith("emblem:"):
        name = name[len("emblem:"):]
        frames = []
        for size in EMBLEM_SIZES:
            half = size // 2
            emblem = Image.open(assets / "legacy" / f"{half}x{half}" / (name + ".png"))
            canvas = Image.new("RGBA", (size, size))
            canvas.paste(emblem.convert("RGBA"), (0, size - half))
            frames.append(canvas)
        return frames
    if name.startswith("legacy:"):
        name = name[len("legacy:"):]
        pngs = [assets / "legacy" / f"{size}x{size}" / (name + ".png") for size in LEGACY_SIZES]
        return [Image.open(png).convert("RGBA") for png in pngs if png.exists()]
    frames = []
    for size in SIZES:
        png = assets / "16x16" / (name + ".png")
        if size == 16 and png.exists():
            frames.append(Image.open(png).convert("RGBA"))
            continue
        data = resvg_py.svg_to_bytes(svg_path=str(assets / "scalable" / (name + ".svg")),
                                     width=size, height=size)
        frames.append(Image.open(io.BytesIO(bytes(data))).convert("RGBA"))
    return frames


def encode(assets, name):
    frames = []
    sizes = []
    for image in frames_for(assets, name):
        size = image.width
        assert image.size == (size, size)
        sizes.append(size)
        rows = []
        stride = ((size + 31) // 32) * 4
        mask = bytearray(stride * size)
        source = image.load()
        for y in range(size - 1, -1, -1):
            row = bytearray()
            for x in range(size):
                r, g, b, a = source[x, y]
                if a == 0:
                    r = g = b = 0
                if a < 128:
                    mask[(size - 1 - y) * stride + x // 8] |= 0x80 >> (x % 8)
                row.extend((b, g, r, a))
            rows.append(bytes(row))
        pixels = b"".join(rows)
        header = struct.pack("<IiiHHIIiiII", 40, size, size * 2,
                             1, 32, 0, len(pixels), 0, 0, 0, 0)
        frames.append(header + pixels + bytes(mask))

    offset = 6 + 16 * len(frames)
    directory = bytearray(struct.pack("<HHH", 0, 1, len(frames)))
    for size, data in zip(sizes, frames):
        directory.extend(struct.pack("<BBBBHHII", size % 256, size % 256,
                                     0, 0, 1, 32, len(data), offset))
        offset += len(data)
    return bytes(directory) + b"".join(frames)


def main():
    assets = Path(__file__).resolve().parent
    root = assets.parents[2]
    cache = {}
    for name, directory, icons in TARGETS:
        if name not in cache:
            cache[name] = encode(assets, name)
        for icon in icons:
            target = directory + str(icon) + ".ico"
            (root / target).write_bytes(cache[name])
            print(name + " -> " + target)


if __name__ == "__main__":
    main()
